import spacy

# Load the model
nlp = spacy.load("en_blackstone_proto")

def get_top_cat(doc):
    """
    Function to identify the highest scoring category
    prediction generated by the text categoriser. 
    """
    cats = doc.cats
    max_score = max(cats.values()) 
    max_cats = [k for k, v in cats.items() if v == max_score]
    max_cat = max_cats[0]
    return (max_cat, max_score)

case = open("/home/tristan/Stage/TextesJuridiques/BordenvUnitedStatesKagan.txt")


# Run the function on the string
text = case.read()

text = text.replace("\n", "")
text = text.replace("\t", " ")

# Apply the model to the text
doc = nlp(text)

# Get the sentences in the passage of text
sentences = [sent.text for sent in doc.sents]


f = open("/home/tristan/Stage/EtudeLogiciels/ExplicationBlackstone/BordenvUSA/BordenvUSA_Kagan.txt", "w")
# Print the sentence and the corresponding predicted category.
for sentence in sentences:
    doc = nlp(sentence)
    top_category = get_top_cat(doc)
    print (f"\"{sentence}\"|{top_category[0]}", file=f)